services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${PYTHON_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${PYTHON_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${PYTHON_DATASOURCE_NAME}
    ports:
      - 5435:5432
    volumes:
      - ./local/postgres-data:/var/lib/postgresql/data
      - ./local/postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PYTHON_DATASOURCE_USERNAME} -d ${PYTHON_DATASOURCE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  scraper:
    build: .
    restart: always
    environment:
      TEAM_API_URL: ${TEAM_API_URL}
      MATCH_API_URL: ${MATCH_API_URL}
      POOL_API_URL: ${POOL_API_URL}
      LOG_LEVEL: ${LOG_LEVEL}
      PYTHON_DATASOURCE_URL: ${PYTHON_DATASOURCE_URL}    
    depends_on:
      postgres:
        condition: service_healthy
        
volumes:
  postgres-data:
