# logging.yaml
version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG  # Niveau de log pour la console
    formatter: simple
    stream: ext://sys.stdout
  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG  # Niveau de log pour le fichier
    formatter: simple
    filename: "logs/app.log"
    maxBytes: 10485760  # 10 MB
    backupCount: 5
    encoding: utf8

loggers:
  myvolley:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: no

root:
  level: WARNING
  handlers: [console]